In [24]:
import pandas as pd
import numpy as np

In [25]:
dataset = pd.read_csv("House Price Prediction Dataset.csv")
dataset.head()

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0   1  1360         5          4       3       1970  Downtown  Excellent   
1   2  4272         5          4       3       1958  Downtown  Excellent   
2   3  3592         2          2       3       1938  Downtown       Good   
3   4   966         4          2       2       1902  Suburban       Fair   
4   5  4926         1          4       2       1975  Downtown       Fair   

  Garage   Price  
0     No  149919  
1     No  424998  
2     No  266746  
3    Yes  244020  
4    Yes  636056

In [26]:
Dheya=dataset.drop(columns=['Location', 'Condition','Garage'])
Dheya

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt   Price
0        1  1360         5          4       3       1970  149919
1        2  4272         5          4       3       1958  424998
2        3  3592         2          2       3       1938  266746
3        4   966         4          2       2       1902  244020
4        5  4926         1          4       2       1975  636056
...    ...   ...       ...        ...     ...        ...     ...
1995  1996  4994         5          4       3       1923  295620
1996  1997  3046         5          2       1       2019  580929
1997  1998  1062         5          1       2       1903  476925
1998  1999  4062         3          1       2       1936  161119
1999  2000  2989         5          1       3       1903  482525

[2000 rows x 7 columns]

In [27]:

X = Dheya.iloc[:,:-1].values
y = Dheya.iloc[:, 3].values

In [28]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_gender =  LabelEncoder()
X[:,0] = labelEncoder_gender.fit_transform(X[:,0])

In [29]:
import numpy as np
X = np.vstack(X[:, ]).astype(float)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [31]:
from sklearn.preprocessing import StandardScaler
ss_X = StandardScaler()
X_train = ss_X.fit_transform(X_train)
X_test = ss_X.transform(X_test)

In [32]:
from sklearn.svm import SVC 
classifier = SVC(kernel = "linear", random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [33]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 3, 1, 3, 3, 1, 2, 2, 2, 3, 3, 4, 2, 2, 2, 3, 1, 2, 1, 2,
       3, 1, 3, 2, 3, 3, 1, 4, 2, 1, 3, 2, 3, 2, 2, 2, 3, 4, 4, 3, 2, 2,
       3, 2, 4, 2, 2, 4, 1, 3, 2, 1, 2, 1, 2, 4, 2, 3, 3, 4, 2, 1, 1, 4,
       4, 3, 3, 1, 4, 2, 2, 1, 2, 1, 1, 2, 3, 1, 3, 1, 1, 3, 1, 3, 2, 2,
       2, 4, 3, 3, 1, 1, 3, 1, 1, 1, 2, 2, 3, 1, 1, 3, 2, 4, 1, 4, 2, 4,
       2, 3, 4, 2, 4, 1, 3, 3, 1, 3, 1, 1, 1, 1, 4, 2, 1, 4, 2, 4, 3, 2,
       3, 3, 3, 1, 3, 2, 1, 1, 4, 3, 2, 1, 1, 1, 3, 2, 4, 2, 4, 2, 3, 3,
       4, 3, 2, 1, 3, 4, 2, 2, 2, 3, 4, 2, 2, 4, 2, 1, 2, 2, 4, 1, 2, 4,
       3, 1, 1, 4, 2, 1, 3, 2, 4, 4, 3, 1, 3, 1, 2, 4, 4, 2, 2, 1, 4, 4,
       3, 4, 3, 2, 2, 2, 1, 1, 3, 4, 3, 3, 4, 4, 2, 3, 4, 2, 4, 3, 1, 2,
       4, 4, 3, 2, 4, 1, 3, 1, 3, 2, 3, 3, 3, 1, 3, 2, 3, 1, 2, 3, 4, 3,
       2, 4, 1, 2, 3, 4, 1, 2, 1, 2, 2, 1, 1, 3, 1, 2, 1, 3, 3, 3, 1, 3,
       2, 4, 2, 3, 1, 2, 4, 1, 3, 1, 4, 2, 2, 1, 4, 1, 3, 2, 4, 1, 3, 1,
       4, 4, 2, 3, 3, 4, 4, 1, 4, 4, 3, 3, 3, 4, 1,

In [34]:
y_test

array([1, 1, 1, 3, 1, 3, 3, 1, 2, 2, 2, 3, 3, 4, 2, 2, 2, 3, 1, 2, 1, 2,
       3, 1, 3, 2, 3, 3, 1, 4, 2, 1, 3, 2, 3, 2, 2, 2, 3, 4, 4, 3, 2, 2,
       3, 2, 4, 2, 2, 4, 1, 3, 2, 1, 2, 1, 2, 4, 2, 3, 3, 4, 2, 1, 1, 4,
       4, 3, 3, 1, 4, 2, 2, 1, 2, 1, 1, 2, 3, 1, 3, 1, 1, 3, 1, 3, 2, 2,
       2, 4, 3, 3, 1, 1, 3, 1, 1, 1, 2, 2, 3, 1, 1, 3, 2, 4, 1, 4, 2, 4,
       2, 3, 4, 2, 4, 1, 3, 3, 1, 3, 1, 1, 1, 1, 4, 2, 1, 4, 2, 4, 3, 2,
       3, 3, 3, 1, 3, 2, 1, 1, 4, 3, 2, 1, 1, 1, 3, 2, 4, 2, 4, 2, 3, 3,
       4, 3, 2, 1, 3, 4, 2, 2, 2, 3, 4, 2, 2, 4, 2, 1, 2, 2, 4, 1, 2, 4,
       3, 1, 1, 4, 2, 1, 3, 2, 4, 4, 3, 1, 3, 1, 2, 4, 4, 2, 2, 1, 4, 4,
       3, 4, 3, 2, 2, 2, 1, 1, 3, 4, 3, 3, 4, 4, 2, 3, 4, 2, 4, 3, 1, 2,
       4, 4, 3, 2, 4, 1, 3, 1, 3, 2, 3, 3, 3, 1, 3, 2, 3, 1, 2, 3, 4, 3,
       2, 4, 1, 2, 3, 4, 1, 2, 1, 2, 2, 1, 1, 3, 1, 2, 1, 3, 3, 3, 1, 3,
       2, 4, 2, 3, 1, 2, 4, 1, 3, 1, 4, 2, 2, 1, 4, 1, 3, 2, 4, 1, 3, 1,
       4, 4, 2, 3, 3, 4, 4, 1, 4, 4, 3, 3, 3, 4, 1,

In [35]:
X_train.shape

(1500, 6)

In [36]:
X_test.shape

(500, 6)

In [37]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred) 
print(cm)
accuracy = metrics.accuracy_score(y_test, y_pred) 
print("Accuracy score:",accuracy)

[[118   0   0   0]
 [  0 136   0   0]
 [  0   0 129   0]
 [  0   0   0 117]]
Accuracy score: 1.0
